language: node_js
node_js:
  - '14'
  - '12'
  - '10'
notifications:
  email: false
branches:
  only:
    - master
addons:
  apt:
    packages:
      - nasm
before_install: if [[ $TRAVIS_OS_NAME == osx ]]; then brew update && brew install nasm; fi;
